version: "3.7"
services:
  # Override defaults so Mariadb is used as the database for this service.
  drupal:
    environment:
      DRUPAL_DEFAULT_DB_DRIVER: mysql
      # Use the edge name so the Drush on the host machine can access it.
      DRUPAL_DEFAULT_DB_PORT: 3306
