version: "3.7"
secrets:
  ACTIVEMQ_PASSWORD:
    file: "./secrets/ACTIVEMQ_PASSWORD"
  ACTIVEMQ_WEB_ADMIN_PASSWORD:
    file: "./secrets/ACTIVEMQ_WEB_ADMIN_PASSWORD"
  ALPACA_ACTIVEMQ_PASSWORD:
    file: "./secrets/ALPACA_ACTIVEMQ_PASSWORD"
  ALPACA_KARAF_ADMIN_PASSWORD:
    file: "./secrets/ALPACA_KARAF_ADMIN_PASSWORD"
  DRUPAL_DEFAULT_ACCOUNT_PASSWORD:
    file: "./secrets/DRUPAL_DEFAULT_ACCOUNT_PASSWORD"
  DRUPAL_DEFAULT_DB_PASSWORD:
    file: "./secrets/DRUPAL_DEFAULT_DB_PASSWORD"
  DRUPAL_DEFAULT_DB_ROOT_PASSWORD:
    file: "./secrets/DRUPAL_DEFAULT_DB_ROOT_PASSWORD"
  DRUPAL_DEFAULT_SALT:
    file: "./secrets/DRUPAL_DEFAULT_SALT"
  DRUPAL_JWT_PRIVATE_KEY:
    file: "./secrets/JWT_PRIVATE_KEY"
  DRUPAL_JWT_PUBLIC_KEY:
    file: "./secrets/JWT_PUBLIC_KEY"
  FCREPO_DB_PASSWORD:
    file: "./secrets/FCREPO_DB_PASSWORD"
  FCREPO_DB_ROOT_PASSWORD:
    file: "./secrets/FCREPO_DB_ROOT_PASSWORD"
  FCREPO_JWT_ADMIN_TOKEN:
    file: "./secrets/JWT_ADMIN_TOKEN"
  FCREPO_JWT_PUBLIC_KEY:
    file: "./secrets/JWT_PUBLIC_KEY"
  GEMINI_DB_PASSWORD:
    file: "./secrets/GEMINI_DB_PASSWORD"
  GEMINI_DB_ROOT_PASSWORD:
    file: "./secrets/GEMINI_DB_ROOT_PASSWORD"
  GEMINI_JWT_ADMIN_TOKEN:
    file: "./secrets/JWT_ADMIN_TOKEN"
  GEMINI_JWT_PUBLIC_KEY:
    file: "./secrets/JWT_PUBLIC_KEY"
  HOMARUS_JWT_ADMIN_TOKEN:
    file: "./secrets/JWT_ADMIN_TOKEN"
  HOMARUS_JWT_PUBLIC_KEY:
    file: "./secrets/JWT_PUBLIC_KEY"
  HOUDINI_JWT_ADMIN_TOKEN:
    file: "./secrets/JWT_ADMIN_TOKEN"
  HOUDINI_JWT_PUBLIC_KEY:
    file: "./secrets/JWT_PUBLIC_KEY"
  HYPERCUBE_JWT_ADMIN_TOKEN:
    file: "./secrets/JWT_ADMIN_TOKEN"
  HYPERCUBE_JWT_PUBLIC_KEY:
    file: "./secrets/JWT_PUBLIC_KEY"
  MYSQL_ROOT_PASSWORD:
    file: "./secrets/MYSQL_ROOT_PASSWORD"
  MATOMO_DB_PASSWORD:
    file: "./secrets/MATOMO_DB_PASSWORD"
  MATOMO_DB_ROOT_PASSWORD:
    file: "./secrets/MATOMO_DB_ROOT_PASSWORD"
  MATOMO_USER_PASS:
    file: "./secrets/MATOMO_USER_PASS"
  MILLINER_JWT_ADMIN_TOKEN:
    file: "./secrets/JWT_ADMIN_TOKEN"
  MILLINER_JWT_PUBLIC_KEY:
    file: "./secrets/JWT_PUBLIC_KEY"
  RECAST_JWT_ADMIN_TOKEN:
    file: "./secrets/JWT_ADMIN_TOKEN"
  RECAST_JWT_PUBLIC_KEY:
    file: "./secrets/JWT_PUBLIC_KEY"
  DRUPAL_DEFAULT_CONFIGDIR:
    file: "./secrets/DRUPAL_DEFAULT_CONFIGDIR"
services:
  activemq:
    secrets:
      - ACTIVEMQ_PASSWORD
      - ACTIVEMQ_WEB_ADMIN_PASSWORD
  alpaca:
    secrets:
      - ALPACA_ACTIVEMQ_PASSWORD
      - ALPACA_KARAF_ADMIN_PASSWORD
  drupal:
    secrets:
      - DRUPAL_DEFAULT_ACCOUNT_PASSWORD
      - DRUPAL_DEFAULT_DB_PASSWORD
      - DRUPAL_DEFAULT_DB_ROOT_PASSWORD
      - DRUPAL_DEFAULT_SALT
      - DRUPAL_JWT_PRIVATE_KEY
      - DRUPAL_JWT_PUBLIC_KEY
      - DRUPAL_DEFAULT_CONFIGDIR
  fcrepo:
    secrets:
      - FCREPO_DB_PASSWORD
      - FCREPO_DB_ROOT_PASSWORD
      - FCREPO_JWT_ADMIN_TOKEN
      - FCREPO_JWT_PUBLIC_KEY
  gemini:
    secrets:
      - GEMINI_DB_PASSWORD
      - GEMINI_DB_ROOT_PASSWORD
      - GEMINI_JWT_ADMIN_TOKEN
      - GEMINI_JWT_PUBLIC_KEY
  homarus:
    secrets:
      - HOMARUS_JWT_ADMIN_TOKEN
      - HOMARUS_JWT_PUBLIC_KEY
  houdini:
    secrets:
      - HOUDINI_JWT_ADMIN_TOKEN
      - HOUDINI_JWT_PUBLIC_KEY
  hypercube:
    secrets:
      - HYPERCUBE_JWT_ADMIN_TOKEN
      - HYPERCUBE_JWT_PUBLIC_KEY
  mariadb:
    secrets:
      - MYSQL_ROOT_PASSWORD
  matomo:
    secrets:
      - MATOMO_DB_PASSWORD
      - MATOMO_DB_ROOT_PASSWORD
      - MATOMO_USER_PASS
  milliner:
    secrets:
      - MILLINER_JWT_ADMIN_TOKEN
      - MILLINER_JWT_PUBLIC_KEY
  recast:
    secrets:
      - RECAST_JWT_ADMIN_TOKEN
      - RECAST_JWT_PUBLIC_KEY
